spring:
  profiles: local
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017
 # mail:
  #  host:
   # username:
    #password:
    #properties:
     # mail:
      #  transport:
       #   protocol:
        #smtp:
         # port:
          #auth:
          #starttls:
           # enable:
            #required:

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

        security: DEBUG

twilio:
  sid:
  token:
  number: +14074557061
